apiVersion: v1
kind: Service
metadata:
  name: pfe-service-back
  labels:
    app: pfe-devops-back-project
spec:
  selector:
    app: pfe-devops-back-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
