apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pfe-deployment-back
spec:
  selector:
    matchLabels:
      app: pfe-devops-back-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: pfe-devops-back-project
    spec:
      containers:
      - name: pfe-devops-back-project
        image: wassim97/wassim-devops-back-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
